FROM jupyter/base-notebook:latest

RUN pip install pandas
RUN pip install opencv-python-headless
RUN pip install pydicom 
RUN pip install scikit-image
RUN pip install holoviews "bokeh>=2.0,<3.0"
RUN pip install panel "bokeh>=2.0,<3.0"
RUN pip install ipywidgets "bokeh>=2.0,<3.0"
RUN pip install hvplot "bokeh>=2.0,<3.0"